- name: Allow Confluence tcp
  command: firewall-cmd --zone=public --permanent --add-port=8090/tcp

- name: Bounce firewalld
  service: name=firewalld state=restarted
  when: "'con01' not in inventory_hostname_short"
